M48
; DRILL file {KiCad (6.0.8)} date Mon Jun  5 07:52:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-05T07:52:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0402
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0421
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X6.65Y-3.7
X6.65Y-3.8
T2
X5.803Y-2.9596
X5.803Y-3.0596
X5.803Y-3.1596
X6.0904Y-3.75
X6.1904Y-3.75
X6.2904Y-3.75
T3
X5.75Y-3.75
X6.8Y-2.95
T0
M30
