M48
; DRILL file {KiCad 7.0.2} date Thu Jun  1 11:51:44 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-01T11:51:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0335
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0402
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.1181
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.1260
%
G90
G05
T1
X4.75Y-3.961
X5.5Y-4.911
X5.8Y-4.611
X5.8Y-4.911
T2
X5.1972Y-3.7614
X5.1972Y-4.3606
X5.2972Y-3.7614
X6.2972Y-3.7614
X6.2972Y-4.3606
T3
X6.55Y-3.961
X6.65Y-3.961
T4
X4.8Y-3.611
X4.8Y-4.861
T5
X4.8Y-4.311
X6.6Y-3.661
X6.6Y-4.861
T0
M30
