M48
; DRILL file {KiCad 9.0.1} date 2025-04-28T22:46:39+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-28T22:46:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
%
G90
G05
T1
X2.27Y-1.8885
X2.27Y-1.9279
T2
X2.095Y-1.645
X2.195Y-1.645
X2.63Y-1.86
X2.73Y-1.86
M30
